server:
  port: 8888

spring:
  main:
    banner-mode: "off"
  jpa:
    hibernate:
      ddl-auto: update
management:
  endpoints:
    web:
      expose: "*"
      # zu lesen im Server mit http://localhost:8888/actuator/beans und weiteren URLs